services:
  - type: web
    name: corestacks-api
    runtime: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17

      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: seu-db
          property: connectionString

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: seu-db
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: seu-db
          property: password

databases:
  - name: seu-db