package br.com.corestacks.agende360.outbox.enums;

public enum OutboxEventType {
	EMAIL_APPOINTMENT_CONFIRMATION,
	EMAIL_APPOINTMENT_REMINDER,
	WHATSAPP_APPOINTMENT_CONFIRMATION,
	WHATSAPP_APPOINTMENT_REMINDER,
	APPOINTMENT_CANCELLED
}