ALTER TABLE company 
ADD COLUMN logradouro 	VARCHAR(100) 	NOT NULL DEFAULT 'N/A',
ADD COLUMN numero 		VARCHAR(10) 	NOT NULL DEFAULT 'N/A',
ADD COLUMN bairro 		VARCHAR(100) 	NOT NULL DEFAULT 'N/A',
ADD COLUMN cidade 		VARCHAR(100) 	NOT NULL DEFAULT 'N/A',
ADD COLUMN estado 		VARCHAR(50) 	NOT NULL DEFAULT 'N/A',
ADD COLUMN CEP 			VARCHAR(15) 	NOT NULL DEFAULT 'N/A';